name: team-formation-app-enhanced
services:
- name: web
  source_dir: /
  github:
    repo: nozdemir/team-formation-app-enhanced
    branch: master
  dockerfile_path: Dockerfile
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  envs:
  - key: FLASK_APP
    value: run.py
  - key: FLASK_ENV
    value: production
  - key: NEO4J_URI
    value: neo4j+s://54f41429.databases.neo4j.io
  - key: NEO4J_USER
    value: neo4j
  - key: NEO4J_PASSWORD
    value: j1fv7zahO1N8ly6efLg0xUfDBQxwTGrQhEuZZn_gPkM